### ISSUE TITLE
Add ability to store srt file in desired location

### ISSUE THREAD

**Issue by japborst** [AssemblyAI/assemblyai-cli#109]
**Please describe your feature request**
At the moment you can use `--srt` in the CLI to generate an srt file at `<id>.srt`. However, I'd like to specify the path the srt file would be stored at.

**Describe alternatives you've considered**
Currently I'm doing the following
```sh
video_path=...
srt_path="${video_path%.*}.srt"
tmp_path=$(assemblyai transcribe <file> --srt | tail -n 1 | awk '{print $NF}')
mv "${tmp_path}" "${srt_path}"
```

**Additional context**
n.a.

**Comment by fcastillo90** [comment]
Hi @japborst! Thank you for taking the time to write about the feature you are looking for. We will be adding this to our roadmap and will let you know as soon as it gets released
