### ISSUE TITLE
panic : runtime error when using assemblyai transcribe "youtube url

### ISSUE THREAD

**Issue by hellbuster45** [AssemblyAI/assemblyai-cli#117]
I'm recieving this output whenever I run the given command ( assemblyai transcribe "youtube url" ) :-

'''
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x95e8db]

goroutine 1 [running]:
github.com/AssemblyAI/assemblyai-cli/utils.YoutubeDownload({0xc00001e440?, 0xc0003755f0?})
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/youtube.go:56 +0x2bb
github.com/AssemblyAI/assemblyai-cli/utils.Transcribe({{0xc00001e420, 0x2b}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
        /home/runner/work/assemblyai-cli/assemblyai-cli/utils/transcribe.go:78 +0x1bf
github.com/AssemblyAI/assemblyai-cli/cmd.glob..func4(0xdf9bc0?, {0xc000301710?, 0x1?, 0x1?})
        /home/runner/work/assemblyai-cli/assemblyai-cli/cmd/transcribe.go:249 +0xcf0
github.com/spf13/cobra.(*Command).execute(0xdf9bc0, {0xc0003016f0, 0x1, 0x1})
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xdf9940)
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/assemblyai-cli/assemblyai-cli/vendor/github.com/spf13/cobra/command.go:918
github.com/AssemblyAI/assemblyai-cli/cmd.Execute()
        /home/runner/work/assemblyai-cli/assemblyai-cli/cmd/root.go:42 +0x85
main.main()
        /home/runner/work/assemblyai-cli/assemblyai-cli/main.go:11 +0x17
'''

**Comment by MLawlz** [comment]
Hi @hellbuster45! Thanks for surfacing this. We're in the process of migrating to a different solution to handle YouTube content since the existing code relies on a deprecated API from Google. I've made a PR [here](https://github.com/AssemblyAI/assemblyai-cli/pull/118) that will be under review soon to help get this addressed in the next update.

**Comment by roblappcoupa** [comment]
What's the status of this? I used to use this cli tool a lot and now it doesn't seem to be working at all on my Windows 11 machine. I was getting the same error shown above, so I re-installed the latest version of the cli. But now, when I run:
```
assemblyai transcribe "https://www.youtube.com/watch?v=0dfdLqCCDSw"
```
it just hangs with no output at all and then eventually outputs this generic error:
```
"Something went wrong. Please try again."
```
This happens every time I try and transcribe. I don't see and flag for enabling diagnostic logging either. So the tool is unusable for me right now.
