### ISSUE TITLE
Why is there no support for the Russian language

### ISSUE THREAD

**Issue by Dmitryi** [AssemblyAI/assemblyai-cli#121]
```
assemblyai transcribe file.mp3 --language_code ru --auto_chapters
The following models are not available in this language: auto_chapters
```
the same goes for
--sentiment_analysis

**Comment by Swimburger** [comment]
Hi, the auto chapters and sentiment analysis model is only supported for the following languages codes at this moment: en, en_au, en_uk, en_us.

You can find [which features and models we support for our supported languages in the tables in the docs](https://www.assemblyai.com/docs/getting-started/supported-languages#supported-languages-for-best).
