### ISSUE TITLE
installation script: download failing on Linux x86_64

### ISSUE THREAD

**Issue by reka** [AssemblyAI/assemblyai-cli#51]
Hi,

I wanted to install the assemblyai-cli on Linux:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/AssemblyAI/assemblyai-cli/main/install.sh)"
```

=>

> Using the OSS distribution...
> Downloading AssemblyAI CLI v1.9.1...

No more output. :slightly_smiling_face: 

## Environment

OS: Ubuntu 22.04

## Troubleshooting

It looks like the script is trying to download
`$RELEASES_URL/download/$VERSION/${FILE_BASENAME}_${VERSION:1}_$(uname -s)_$(uname -m).tar.gz`

https://github.com/AssemblyAI/assemblyai-cli/blob/main/install.sh#L25

In my env:

```
uname -s
```

=>
Linux

```
uname -m
```

=>

x86_64

But there's no version to download with the suffix "linux_x86_64.tar.gz" among the [releases](https://github.com/AssemblyAI/assemblyai-cli/releases)

**Comment by fcastillo90** [comment]
Hi @reka! Thank you for reporting this issue.
We have already opened a PR for fixing it. We'll let you know as soon as it gets approved and merged for you to try again - most likely later today.
