### ISSUE TITLE
MAC Montery 12.6: Something went wrong. Please try again. 

### ISSUE THREAD

**Issue by quito96** [AssemblyAI/assemblyai-cli#56]
Installed latest Xcode CLI and assenblyai 
with
```
brew tap assemblyai/assemblyai
brew install assemblyai
```
Unfortunately it doesn't work on my mac. 
Message :
```
 ~ % assemblyai transcribe https://youtu.be/0wvBu014E5o -auto_highlights - entity_detection
Transcribing a youtube video....
Something went wrong. Please try again. 
```
I try several youtube links.

local mp3 file transcripts have works

**Comment by SimplyJuanjo** [comment]
Got the same bug in Ubuntu22:

ROG-Strix-G513QM-G513QM:~/.assemblyai-cli$ ./assemblyai transcribe https://www.youtube.com/watch?v=0dfdLqCCDSw
Transcribing Youtube video...
Something went wrong. Please try again.

**Comment by SimplyJuanjo** [comment]
AssemblyAI CLI v1.10.1 yep

ROG-Strix-G513QM-G513QM:~/.assemblyai-cli$ ./assemblyai transcribe "https://www.youtube.com/watch?v=0dfdLqCCDSw"
Transcribing Youtube video...
Something went wrong. Please try again.

Same output

**Comment by quito96** [comment]
Hey @albtsantos ,

``` bash
assemblyai --version
AssemblyAI CLI v1.10.1


assemblyai transcribe "https://youtu.be/0wvBu014E5o"
Transcribing Youtube video...
Something went wrong. Please try again.

assemblyai transcribe "https://www.youtube.com/watch?v=0dfdLqCCDSw"
Transcribing Youtube video...
Something went wrong. Please try again.

```

**Comment by fcastillo90** [comment]
Hey guys @quito96 @SimplyJuanjo ! We just released v1.10.2 which addresses the read and write permissions for the current user, please feel free to update your CLI and try again! If the problem persists, please reopen this thread and we will investigate further on the issue

**Comment by quito96** [comment]
Hey @fcastillo90 , thanks and works really great. I love it

**Comment by SimplyJuanjo** [comment]
Hey @fcastillo90 @albtsantos!

I think the problem is still happening in Ubuntu 22.04

`
(base) juanjo@juanjo-ROG-Strix-G513QM-G513QM:~/.assemblyai-cli$ ./assemblyai -v
`
AssemblyAI CLI v1.10.2
`
(base) juanjo@juanjo-ROG-Strix-G513QM-G513QM:~/.assemblyai-cli$ ./assemblyai transcribe 
"https://www.youtube.com/watch?v=0dfdLqCCDSw"`
Transcribing Youtube video...
Something went wrong. Please try again.
