### ISSUE TITLE
The JSON files have an unnecessary line at the top

### ISSUE THREAD

**Issue by prime-optimal** [AssemblyAI/assemblyai-cli#60]
Please forgive me if I am missing some other obvious way of processing the json.

**Describe the bug**
Using the -j flag on the get command for a transcript adds a line "Transcribing file with id rxzk61qto3-0573-48f4-824e-2a161985ef53" which causes jq (JSON parser) to return an error.

IMO, this line is unnecessary or there should be an option to remove it.

**To Reproduce**
1. Install jq to parse the JSON
2. Run assemblyai get {transcript ID} -j > id.json
3. jq . id.json
4. parse error: Invalid numeric literal at line 1, column 13

**Expected behavior**
jq should parse the transcript's json file without issue.

**Desktop (please complete the following information):**
 - OS: macOS
 - CLI Version v1.10.2

**Additional context**
If there's another workflow that I'm unaware of to process the output (whether it uses json or not), please let me know!

**Comment by fcastillo90** [comment]
Hi @prime-optimal, thanks for bringing this up. We will be addressing this issue in our next release, which will be mid this week. Once the release is out, we will ping you for you to try it out!

**Comment by fcastillo90** [comment]
Hey @prime-optimal ! We just released v1.12.1 of the CLI, which includes the fix for the issue of exporting the JSON file! Please feel free to update and try it out! In case the problem persists, please let us know reopening this issue

**Comment by prime-optimal** [comment]
Ayyyy, it works!  Thanks so much!
