### ISSUE TITLE
Add word boost and custom vocabulary

### ISSUE THREAD

**Issue by prime-optimal** [AssemblyAI/assemblyai-cli#61]
**Please describe your feature request**
Word boost and custom vocabulary are two really important features of AssemblyAI (and other transcription services) but are for some reason not included in assemblyai-cli.  Having these features would make scripting it WAY easier in my opinion. 

**Describe alternatives you've considered**
I tried using curl requests, but find it to be too cumbersome compared to the ease of assemblyai-cli.  

**Additional context**
I have tweaked yt-dlp extensively to be able to download videos and embed metadata, so being able to transcribe them via the cli would improve the ability to catalog clips effectively.  All the other features are great and I use them, but many niches have lots of custom vocabulary.

**Comment by fcastillo90** [comment]
Hi @prime-optimal! Excellent suggestion! We will work on it and it will be added to our next release (mid this week). As soon as the release is live, we will ping you for you to try

**Comment by fcastillo90** [comment]
Hey @prime-optimal ! We just released v1.12.1 which includes the addition of custom vocabulary. Please feel free to update and try it out!

**Comment by prime-optimal** [comment]
Thanks so much for putting this in there!

There's a minor issue where if you use -k parameter without the -z parameter, it returns an error.  Not a big deal, as I figured it out after a few tries, but perhaps this should be noted in the documentation, as the CLI doesn't give very much info about errors when they occur.  

Thanks again for adding this in there!
