### ISSUE TITLE
Support writing transcribed text to a file.

### ISSUE THREAD

**Issue by Horlarwumhe** [AssemblyAI/assemblyai-cli#83]
**Please describe your feature request**

Add output file flag to write the transcribe text. Currently assemblyai write the text to stdout.

This can be done with bash redirect
```
assemblyai transcribe audio.mp4 > file.txt
```
I think it is good to support this out of box 
```
assemblyai transcribe audio.mp4 --output file.txt
```
The flag name for the output can be `-f`,`--output-file` or any other.

Checks need to be performed if the flag is given before transcribing. Like checking the file doesn't exist, also the folder exists in case of `output some/path/to/file.txt`. Check `some/path/to/` exists, but `file.txt` doesn't exists in the folder. Check permission to write/create file.txt before transcribing.

**Comment by fcastillo90** [comment]
Hi @Horlarwumhe! Thank you for submitting this suggestion, we already have this feature on our scope for future release. I'll make sure to ping you as soon as it gets implemented. Will close this issue until then
