### ISSUE TITLE
Error parsing custom spelling file

### ISSUE THREAD

**Issue by BuzzTea89** [AssemblyAI/assemblyai-cli#93]
I want test the flag "--custom_spelling ./custom_spelling.json", but I got an Error:
"Error parsing custom spelling file"

The json file just contains the example from here:
https://www.assemblyai.com/docs/core-transcription#custom-spelling

What am I doing wrong?

**Comment by BuzzTea89** [comment]
Still got the error. :(

**Comment by fcastillo90** [comment]
Hello there @BuzzTea89 ! Sorry for the inconvenience, but the actual syntax for the custom spelling would be the following:

- through a file like the following: `--custom_spelling ./spelling.json` with this structure:
```
[
  {
    "from": [
      "ariana"
    ],
    "to": "Arianna"
  }
]
```

- Or inline `--custom_spelling "[{\"from\": [\"ariana\"], \"to\": \"Arianna\"}]"`

Either of them works, give it a try and if the problem persists, please reopen this issue

**Comment by BuzzTea89** [comment]
It works, thanks a lot! :)
